ALTER TABLE `data_sources` MODIFY COLUMN `status` enum('READY','CURRENT','STALE','DATA REQUIRED','ERROR') NOT NULL DEFAULT 'DATA REQUIRED';--> statement-breakpoint
ALTER TABLE `data_sources` ADD `lastAttemptedAt` timestamp;--> statement-breakpoint
ALTER TABLE `data_sources` ADD `lastSuccessfulUpdate` timestamp;--> statement-breakpoint
ALTER TABLE `data_sources` ADD `recordCount` int DEFAULT 0;--> statement-breakpoint
ALTER TABLE `data_sources` ADD `lastError` text;--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `fx_rates` ADD `rawValue` text;--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `historical_prices` ADD `rawValue` text;--> statement-breakpoint
ALTER TABLE `market_data` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `market_data` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `market_data` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `market_data` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `market_data` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `market_data` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `market_data` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `market_data` ADD `rawValue` text;--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `treasury_bills` ADD `rawValue` text;--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `treasury_bonds` ADD `rawValue` text;--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `observationDate` timestamp;--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `publicationTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `retrievalTimestamp` timestamp;--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `frequency` varchar(32);--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `currency` varchar(8);--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `sourceUrl` text;--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `ingestionStatus` varchar(32);--> statement-breakpoint
ALTER TABLE `yield_curve` ADD `rawValue` text;